### ISSUE TITLE
contributing guidelines

### ISSUE THREAD

**Issue by whbdupree** [mozman/bintrees#4]
I want to add some functionality. Would you be interested in a pull request? Or should I create a `bintrees-extras` package that depends on bintrees.

I want the option for ct_compare to cast strings to float before comparison so that strings that contain numerical data are sorted numerically rather than lexically.

**Comment by mozman** [comment]
Hi!

bintrees is in maintenace only mode, no new features will be added.

But you can wrap your data into a custom class with your own comparison methods.
