### ISSUE TITLE
 Failed building wheel for bintrees

### ISSUE THREAD

**Issue by wheeeee** [mozman/bintrees#5]
i always get this error trying to install bintrees. on mac with anaconda. pip, conda on newest version. any ideas?

Command *path*/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/m9/v2wz_z356k732q0kl6rh2cdr0000gn/T/pip-build-8frgn_9p/bintrees/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/m9/v2wz_z356k732q0kl6rh2cdr0000gn/T/pip-_6sz72j7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/m9/v2wz_z356k732q0kl6rh2cdr0000gn/T/pip-build-8frgn_9p/bintrees/

**Comment by mozman** [comment]
Sorry I can not help, I don't use bintrees anymore and I don't use anaconda.

I recommend using sortedcontainers instead:  https://pypi.python.org/pypi/sortedcontainers,
faster and no compiler dependencies.

**Comment by wheeeee** [comment]
thank you for your answer. It worked on my linux server, so thats all I needed.
