### ISSUE TITLE
Documentation on how to build cython fastrees?

### ISSUE THREAD

**Issue by mattdornfeld** [mozman/bintrees#6]
It seems like the process for getting the fast trees were working involves building cython code? Could we get an example of how to do so?

**Comment by mozman** [comment]
`python setup.py install` should build the C extension if you have installed Cython

Please consider using `sortedcontainers`:  [Sorted Containers](http://www.grantjenks.com/docs/sortedcontainers/) is an Apache2 licensed sorted collections library, written in pure-Python, and fast as C-extensions.
